/**
 * Mirrors SchoolManagment.Models/DTOs/Parents and the procedures in
 * `17_Procs_Parents.sql`.
 *
 * As everywhere else, the school is absent from these shapes: `SchoolId` comes from the
 * token and the API takes it from there.
 *
 * **Two ids per parent, and the API is not consistent about which it wants.**
 * `id` is `Parents.Id` and `userId` is `Users.Id`. Every write, the children read and the
 * link/unlink calls are keyed on `id`; the two profile reads are keyed on `userId`. That
 * is why the profile route is `/parents/:userId` -- the screen it opens is the thing that
 * can only be fetched by the user id. It is the same split as Teachers.
 */

/** Father, Mother or Guardian -- `CK_StudentParents_Relationship` allows nothing else. */
export const RELATIONSHIPS = ['Father', 'Mother', 'Guardian'] as const
export type Relationship = (typeof RELATIONSHIPS)[number]

/**
 * DTOs/Parents/ParentDTO.cs, as `sp_GetAllParents`, `sp_GetParentById` and
 * `sp_GetParentsByStudent` return it -- the same column list in all three, so one row type
 * serves the list, the per-student contacts panel and the edit dialog.
 *
 * Unlike `TeacherRow`, `isActive` here is a real distinction: `sp_GetAllParents` takes
 * `@IncludeInactive`, so a deactivated parent can be listed. The list screen has a status
 * filter for exactly that reason.
 */
export interface ParentRow {
  /** `Parents.Id`. The id every write takes. */
  id: number
  occupation: string | null
  /** Rupees per year, `DECIMAL(12,2)`. Null when nobody recorded it, which is not 0. */
  annualIncome: number | null
  isActive: boolean
  /** `Users.Id`. What the profile endpoints are keyed on. */
  userId: number
  username: string
  email: string
  firstName: string
  lastName: string
  phoneNumber: string | null
  address: string | null
  /**
   * Comma-joined names of the active, non-deleted children, built by the procedure with
   * STRING_AGG. Null when there are none -- see `childrenCount`.
   */
  childrenNames: string | null
  childrenCount: number
  /**
   * Only populated by `GET /api/Parents/student/{studentId}`, and null everywhere else.
   *
   * The relationship belongs to the link row rather than to the person: the same adult can
   * be a Father to one child and a Guardian to another, so there is no single answer to put
   * on a whole-school list. `sp_GetAllParents` selects it as an explicit NULL to keep the
   * column shape identical across the three reads.
   */
  relationship: string | null
  schoolId: number
  createdAt: string
  updatedAt: string
}

/**
 * DTOs/Parents/ParentRegistrationDTO.cs, which is also ParentUpdateDTO plus `password` --
 * so one payload type and one dialog serve registration and the admin edit.
 *
 * `sp_UpdateParent` writes every column it is given, so this is a replacement rather than
 * a patch: a box left empty clears what is on file. The phone number is cleared
 * explicitly by the procedure rather than through `sp_UpsertPerson`, which treats null as
 * "leave alone" -- so an emptied phone box really does empty the phone.
 */
export interface ParentPayload {
  firstName: string
  lastName: string
  email: string
  phoneNumber?: string | null
  address?: string | null
  occupation?: string | null
  annualIncome?: number | null
  /**
   * Registration only, and not offered by the dialog: left unset, the service hashes the
   * shared temporary password and the parent lands on the forced-change screen at their
   * first sign-in. It is on the DTO, so it is here, but a password chosen by an admin is a
   * password that has to be communicated in the clear.
   */
  password?: string | null
}

/** DTOs/Parents/ParentRegistrationResponseDTO.cs. */
export interface ParentRegistrationResult {
  /** `Users.Id` -- what the new parent's profile route needs. */
  userId: number
  /** `Parents.Id` -- what the link and children calls need. */
  parentId: number
  /** Generated by the server from the name, e.g. `DPSNOIDA_P_RSHARMA01`. */
  username: string
}

/**
 * DTOs/Parents/ParentProfileDTO.cs -> ParentChildDTO, as both
 * `sp_GetChildrenByParent` and the profile's second result set return it.
 *
 * `className`, `grade` and `section` are non-nullable on the DTO and the procedures send
 * `''` for a student who is between classes, so an empty string means "not placed" rather
 * than "not loaded".
 */
export interface ParentChild {
  /** `Students.Id` -- what `/students/:studentId` takes. */
  studentId: number
  /** The printed admission number, e.g. `STU2026001`. Not the record id. */
  studentNumber: string
  firstName: string
  lastName: string
  email: string
  className: string
  grade: string
  section: string
  /** Always filled here: it is read straight off the link row. */
  relationship: string
}

/**
 * DTOs/Parents/ParentProfileDTO.cs.
 *
 * No `stats` counterpart to `TeacherProfile.stats`: there is no parent statistics
 * procedure, and the children list is the whole of the second result set.
 *
 * `sp_GetParentProfile` does **not** filter on `IsActive`, so unlike the teacher profile
 * this opens for a deactivated parent -- which is what makes the list's "deactivated"
 * filter lead somewhere.
 */
export interface ParentProfile {
  /** `Parents.Id`. */
  id: number
  occupation: string | null
  annualIncome: number | null
  isActive: boolean
  createdAt: string
  updatedAt: string
  userId: number
  username: string
  email: string
  firstName: string
  lastName: string
  phoneNumber: string | null
  address: string | null
  requirePasswordChange: boolean
  schoolId: number
  schoolCode: string | null
  schoolName: string | null
  /** Active links to active students only. Empty for a parent with nobody attached. */
  children: ParentChild[]
}

/**
 * DTOs/Parents/LinkStudentParentDTO.cs.
 *
 * `sp_LinkStudentParent` is a MERGE on `(SchoolId, StudentId, ParentId)`, so this both
 * creates a link and re-labels or re-activates one that already exists -- posting the same
 * pair with a different relationship corrects it rather than failing on `UQ_StudentParents`.
 */
export interface LinkStudentParentPayload {
  studentId: number
  parentId: number
  relationship: Relationship
}

/** DTOs/Parents/UnlinkStudentParentDTO.cs. Deactivates the link; the row is kept. */
export interface UnlinkStudentParentPayload {
  studentId: number
  parentId: number
}

/** "Priya Sharma (DPSNOIDA_P_PSHARMA01)" -- the username disambiguates two of one name. */
export function parentLabel(
  parent: Pick<ParentRow, 'firstName' | 'lastName' | 'username'>,
): string {
  const name = `${parent.firstName} ${parent.lastName}`.trim()
  return name ? `${name} (${parent.username})` : parent.username
}

/**
 * The children as an array of names, from the comma-joined string the list endpoint sends.
 *
 * Kept here rather than in the page so the "no children" case (null, not `''`) cannot
 * become `['']` and render as one empty chip.
 */
export function childrenNameList(parent: Pick<ParentRow, 'childrenNames'>): string[] {
  if (!parent.childrenNames) return []
  return parent.childrenNames
    .split(',')
    .map((name) => name.trim())
    .filter((name) => name !== '')
}
