/**
 * Mirrors SchoolManagment.Models/DTOs/Students and the procedures behind them.
 *
 * As everywhere else, the school is absent from these shapes: `SchoolId` comes from the
 * token and the API takes it from there.
 */

/**
 * DTOs/Students/StudentDTO.cs, as `sp_GetAllStudents`, `sp_GetStudentById` and
 * `sp_GetStudentsByClass` all return it -- the same column list in all three, so one row
 * type serves the list, the picker and the profile header.
 *
 * Two ids live on this row and confusing them is the module's classic bug: `id` is the
 * `Students` primary key, which every endpoint path takes, while `studentId` is the
 * printed admission number (`STU2026001`).
 */
export interface StudentRow {
  id: number
  /** The `Users` row behind the student: what the profile picture and login belong to. */
  userId: number
  /** The admission number, a string. Not the record id. */
  studentId: string
  username: string
  firstName: string
  lastName: string
  email: string
  phoneNumber: string | null
  /** Null for a student admitted but not yet placed in a class. */
  classId: number | null
  className: string | null
  /** Unique within a class, and reallocated when the student is promoted. */
  rollNumber: string | null
  dateOfBirth: string | null
  /** `Male`, `Female` or `Other` -- CK_Students_Gender allows nothing else. */
  gender: string | null
  fatherName: string | null
  motherName: string | null
  admissionDate: string
  bloodGroup: string | null
  address: string | null
  isActive: boolean
  createdAt: string
  updatedAt: string
}

/** Query string for `GET /api/Students`. */
export interface StudentListQuery {
  classId?: number
  isActive?: boolean
  /** Matches name, email, username, admission number or roll number. */
  searchTerm?: string
  page?: number
  pageSize?: number
}

/**
 * DTOs/Students/StudentRegistrationDTO.cs.
 *
 * `classId` is `[Required]`: a student is registered into a class, because that is what
 * their roll number is allocated from. `password` is optional -- omitted, the server
 * creates the account with the shared temporary password and the first login lands on
 * the forced change screen.
 */
export interface StudentRegistrationPayload {
  firstName: string
  lastName: string
  email: string
  phoneNumber?: string | null
  /** Date-only, `yyyy-MM-dd`. */
  dateOfBirth: string
  gender: string
  classId: number
  fatherName?: string | null
  motherName?: string | null
  bloodGroup?: string | null
  address?: string | null
  password?: string | null
}

/**
 * DTOs/Students/StudentUpdateDTO.cs.
 *
 * Deliberately **without** `classId`: moving a student between classes is promotion, which
 * has to reallocate the roll number and prune subject enrolments. An update that quietly
 * changed the class would leave the old class's roll number on the student, and
 * `UX_Students_School_Class_Roll` would eventually refuse the next admission.
 */
export interface StudentUpdatePayload {
  firstName: string
  lastName: string
  email: string
  phoneNumber?: string | null
  dateOfBirth?: string | null
  gender?: string | null
  fatherName?: string | null
  motherName?: string | null
  bloodGroup?: string | null
  address?: string | null
}

/** DTOs/Students/StudentRegistrationResponseDTO.cs. */
export interface StudentRegistrationResult {
  /** The `Students` record id -- the one the routes use. */
  studentId: number
  userId: number
  /** Generated by the server; the student signs in with this. */
  username: string
  /** The admission number. */
  studentIdNumber: string
  rollNumber: string | null
  className: string
}

/** DTOs/Students/StudentPromoteDTO.cs. Both fields are `[Required]`. */
export interface StudentPromotePayload {
  newClassId: number
  /**
   * Recorded in the audit trail only -- there is no promotion-history table, so this is
   * how "promoted to 11-A for 2026" stays answerable later.
   */
  academicYear: number
}

/**
 * DTOs/Students/StudentProfileDTO.cs -> AcademicStatsDTO.
 *
 * `averageMarks` is a **percentage**, not a raw mark: the procedure divides obtained
 * marks by the examinations' maximum, because marks out of 50 and out of 100 cannot be
 * averaged together. It and `grade` and `rank` are all null until results exist, and
 * `rank` is also null for a student with no class.
 */
export interface AcademicStats {
  totalSubjects: number
  averageMarks: number | null
  grade: string | null
  /** Position within the class, competition-ranked (two firsts, then third). */
  rank: number | null
  /** 0 when nothing has been marked, which is not the same as 0% attendance. */
  attendancePercentage: number
}

/**
 * DTOs/Students/StudentProfileDTO.cs -> SubjectDTO. Narrower than the Subjects module's
 * own row: this is what `sp_GetStudentSubjects` and the profile's third result set send.
 */
export interface StudentSubject {
  /** The **Subjects.Id**, not the StudentSubjects link id. */
  id: number
  subjectName: string
  subjectCode: string
}

/** DTOs/Students/StudentProfileDTO.cs -> FeeStatusDTO. */
export interface FeeStatus {
  totalDue: number
  totalPaid: number
  /** Sum of per-fee balances, each floored at zero, so an overpayment cannot mask a debt. */
  pendingFees: number
}

/** DTOs/Students/StudentProfileDTO.cs. Every section is independently nullable. */
export interface StudentProfile {
  studentInfo: StudentRow | null
  academicStats: AcademicStats | null
  subjects: StudentSubject[] | null
  feeStatus: FeeStatus | null
}
