/**
 * Mirrors SchoolManagment.Models/DTOs/Teachers and the procedures behind them.
 *
 * As everywhere else, the school is absent from these shapes: `SchoolId` comes from the
 * token and the API takes it from there.
 *
 * **Two ids per teacher, and the API is not consistent about which it wants.**
 * `id` is `Teachers.Id` and `userId` is `Users.Id`. Every write and every assignment
 * endpoint is keyed on `id`; the two profile reads are keyed on `userId`. That is why the
 * profile route is `/teachers/:userId` -- the screen it opens is the thing that can only
 * be fetched by the user id.
 */

/**
 * DTOs/Teachers/TeacherDTO.cs, as `sp_GetTeachersWithDetails` returns it.
 *
 * Only ever an active teacher: the procedure hard-filters `Teachers.IsActive = 1 AND
 * Users.IsActive = 1`, so `isActive` is always true here and a deleted teacher simply
 * is not in the list. There is no status filter on this module for the same reason.
 */
export interface TeacherRow {
  /** `Teachers.Id`. The id every write takes. */
  id: number
  /** The employee number allocated from the school's sequence, e.g. `EMP2026004`. */
  employeeId: string
  /**
   * `Teachers.Subject` -- free text, and a legacy display field. The real subject
   * assignment is the `TeacherSubjects` link set, which arrives as `subjectNames`.
   */
  subject: string | null
  qualification: string | null
  /** Years. `[Range(0, 50)]` on both write DTOs. */
  experience: number | null
  salary: number | null
  /** Defaults to the registration date; there is no endpoint that changes it. */
  joinDate: string | null
  isActive: boolean
  /** `Users.Id`. What the profile endpoints are keyed on. */
  userId: number
  username: string
  email: string
  firstName: string
  lastName: string
  phoneNumber: string | null
  address: string | null
  requirePasswordChange: boolean
  /** Comma-joined subject names, built by the procedure. Null when none are assigned. */
  subjectNames: string | null
  /** The same links as comma-joined ids -- a string, not an array. See `subjectIdList`. */
  subjectIds: string | null
  schoolId: number
}

/**
 * `subjectIds` arrives as `"3,7,12"` because the procedure builds it with STRING_AGG.
 * Parsing it here keeps every caller from re-deriving the split, and keeps the "no
 * subjects" case (null) from becoming `[NaN]`.
 */
export function subjectIdList(teacher: Pick<TeacherRow, 'subjectIds'>): number[] {
  if (!teacher.subjectIds) return []
  return teacher.subjectIds
    .split(',')
    .map((part) => Number(part.trim()))
    .filter((id) => Number.isInteger(id) && id > 0)
}

/**
 * DTOs/Teachers/TeacherRegistrationDTO.cs, which is also TeacherUpdateDTO -- the two are
 * field-for-field identical, so one payload type and one dialog serve both.
 *
 * `subjectIds` is a **replacement** set, not an addition: the procedure forwards it to
 * `sp_AssignSubjectsToTeacher`, which deactivates every link absent from the list. Sent
 * as null (or omitted) on an update, the links are left alone.
 */
export interface TeacherPayload {
  firstName: string
  lastName: string
  email: string
  phoneNumber?: string | null
  address?: string | null
  /** Free text, max 100. The display field, not the link set. */
  subject?: string | null
  qualification?: string | null
  experience?: number | null
  salary?: number | null
  subjectIds?: number[] | null
}

/**
 * The self-service half of the same DTO. Salary is absent on purpose, not by oversight:
 * `sp_UpdateTeacherProfile` does not take it, so a teacher cannot change their own pay.
 * `subjectIds` is absent for the same reason -- they cannot hand themselves a subject.
 */
export type TeacherProfilePayload = Omit<TeacherPayload, 'salary' | 'subjectIds'>

/** DTOs/Teachers/TeacherRegistrationResponseDTO.cs. */
export interface TeacherRegistrationResult {
  /** `Users.Id` -- what the new teacher's profile route needs. */
  userId: number
  /** `Teachers.Id` -- what the subject and class assignment calls need. */
  teacherRecordId: number
  /** Generated by the server from the name; the teacher signs in with this. */
  username: string
  employeeId: string
}

/**
 * DTOs/Teachers/TeacherProfileDTO.cs -> TeacherProfileStatsDTO.
 *
 * All five are counts, so 0 is a real answer rather than a missing one. Two are windowed
 * to the last month and describe activity, not totals:
 *
 *  - `attendanceMarkedLastMonth` counts rows where `Attendance.MarkedBy` is this teacher's
 *    **user** id, so it credits whoever took the register, not whoever owns the class.
 *  - `resultsEnteredLastMonth` counts the same way for marks.
 *
 * `studentsUnderCare` is the roll of the classes they are class teacher of -- not everyone
 * they teach, which would be the subject-class assignments instead.
 */
export interface TeacherStats {
  classesAssigned: number
  studentsUnderCare: number
  subjectsAssigned: number
  attendanceMarkedLastMonth: number
  resultsEnteredLastMonth: number
}

/**
 * DTOs/Teachers/TeacherProfileDTO.cs.
 *
 * `sp_GetTeacherProfile` filters `Teachers.IsActive = 1`, so unlike the student profile
 * this returns nothing at all for a deleted teacher -- the screen 404s rather than
 * showing a deactivated record.
 */
export interface TeacherProfile {
  id: number
  employeeId: string
  subject: string | null
  qualification: string | null
  experience: number | null
  salary: number | null
  joinDate: string | null
  isActive: boolean
  userId: number
  username: string
  email: string
  firstName: string
  lastName: string
  phoneNumber: string | null
  address: string | null
  requirePasswordChange: boolean
  createdAt: string
  updatedAt: string
  /** Comma-joined names from `TeacherSubjects`. Null when none. */
  assignedSubjects: string | null
  /** Comma-joined names of the classes they are class teacher of. Null when none. */
  assignedClasses: string | null
  schoolId: number
  schoolCode: string | null
  schoolName: string | null
  /** Attached by the service from a second procedure; null if that read came back empty. */
  stats: TeacherStats | null
}

/**
 * DTOs/Teachers/TeacherSubjectDTO.cs, as `sp_GetTeacherSubjects` returns it.
 *
 * `isAssigned` is always true in this response: the procedure filters
 * `TeacherSubjects.IsActive = 1`, so a withdrawn link is absent rather than flagged. The
 * column exists for a "every subject, ticked or not" screen that no endpoint serves.
 */
export interface TeacherSubject {
  /** `Subjects.Id`, not the link row's id -- that is `teacherSubjectId`. */
  id: number
  subjectName: string
  subjectCode: string
  grade: string
  /** The subject's own status. A deactivated subject keeps its teacher links. */
  isActive: boolean
  teacherSubjectId: number
  isAssigned: boolean
}

/**
 * DTOs/Teachers/TeacherClassDTO.cs -- the classes this teacher is **class teacher** of,
 * from `Classes.ClassTeacherId`. Not the classes they teach a subject in.
 */
export interface TeacherClass {
  /** `Classes.Id`. */
  id: number
  className: string
  grade: string
  section: string
  maxStudents: number
  studentCount: number
}

/**
 * DTOs/Teachers/TeacherSubjectClassDTO.cs -- one row of the subject-in-class matrix, from
 * `TeacherSubjectAssignments`.
 *
 * This table is what gates mark entry: `sp_GetStudentsForGradeEntry` reads it, so a
 * teacher with no row here cannot enter marks for that class however many subjects they
 * hold.
 */
export interface TeacherSubjectClass {
  /** The assignment row's own id. */
  id: number
  teacherId: number
  subjectId: number
  classId: number
  subjectName: string
  subjectCode: string
  subjectGrade: string
  className: string
  classGrade: string
  section: string
  studentCount: number
}

/**
 * DTOs/Teachers/TeacherClassSubjectAssignmentDTO.cs.
 *
 * `isActive: false` is the un-assign path. `sp_AssignTeacherToSubjectClass` is a MERGE on
 * (teacher, subject, class) and there is no DELETE endpoint, so withdrawing an assignment
 * means posting the same three ids again with the flag off.
 */
export interface TeacherSubjectClassPayload {
  teacherId: number
  subjectId: number
  classId: number
  isActive: boolean
}
